name: CD - Deploy to Salesforce

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Write JWT key
        run: |
          mkdir -p assets
          echo "${{ secrets.SF_JWT_KEY }}" > assets/server.key

      - name: Authenticate to Salesforce (JWT)
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwt-key-file assets/server.key \
            --username "${{ secrets.SF_USERNAME }}" \
            --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
            --set-default

      - name: Deploy
        run: |
          sf project deploy start \
            --source-dir force-app \
            --test-level RunLocalTests
